<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{

    /**
     * Created By : Nilaksha 
     * Created At : 2/2/2021
     * Summary : Fills the datatabes with pre set of data
     *
     * @return void
     */
    public function run()
    {
        // To run the seeds, php artisan db:seed to

        DB::table('roles')->insert([
            ['id' => '1', 'name' => 'Senior Client Service Agent', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '2', 'name' => 'Client Service Agent', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '3', 'name' => 'Finance Manager', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '4', 'name' => 'Receptionist', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '5', 'name' => 'Client', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ]);

        DB::table('user_types')->insert([
            ['id' => '1', 'name' => 'Within Sussex', 'fee' => '12', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '2', 'name' => 'Out of Region', 'fee' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ]);

        DB::table('channels')->insert([
            ['id' => '1', 'name' => 'Telephone', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '2', 'name' => 'Fax', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '3', 'name' => 'Post', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '4', 'name' => 'Email', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '5', 'name' => 'Web Form', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ]);

        DB::table('payment_status')->insert([
            ['id' => '1', 'name' => 'Successful', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '2', 'name' => 'Failed', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ]);

        DB::table('status')->insert([
            ['id' => '1', 'name' => 'Completed', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '2', 'name' => 'Partial', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ]);

        DB::table('event_types')->insert([
            ['id' => '1', 'name' => 'Coastal walks', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '2', 'name' => 'Yatch Trips', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '3', 'name' => 'Sky Diving', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '4', 'name' => 'Rock Climbing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '5', 'name' => 'Evening Lectures', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ]);

        DB::table('hobbies')->insert([
            ['id' => '1', 'name' => 'Abseling', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '2', 'name' => 'Acrobatics', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '3', 'name' => 'Acroyoga', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '4', 'name' => 'Acting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '5', 'name' => 'Aeromodelling', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '6', 'name' => 'Airbrushing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '7', 'name' => 'Aircraft Spotting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '8', 'name' => 'Airplane Combat', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '9', 'name' => 'Airplane Flight', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '10', 'name' => 'Airsofting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '11', 'name' => 'Alligator Wrestling', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '12', 'name' => 'Amateur Astronomy', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '13', 'name' => 'Amateur Radio', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '14', 'name' => 'Animals/pets/dogs', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '15', 'name' => 'Ant Farm', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '16', 'name' => 'Aquarium (Freshwater & Saltwater)', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '17', 'name' => 'Archery', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '18', 'name' => 'Arts', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '19', 'name' => 'Astrology', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '20', 'name' => 'Astronomy', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '21', 'name' => 'Backgammon', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '22', 'name' => 'Badminton', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '23', 'name' => 'Barefooting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '24', 'name' => 'Base Jumping', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '25', 'name' => 'Baseball', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '26', 'name' => 'Basketball', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '27', 'name' => 'Beach/Sun tanning', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '28', 'name' => 'Beachcombing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '29', 'name' => 'Beadwork', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '30', 'name' => 'Beatboxing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '31', 'name' => 'Becoming A Child Advocate', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '32', 'name' => 'Bell Ringing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '33', 'name' => 'Belly ', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '34', 'name' => 'Bicycle Polo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '35', 'name' => 'Bird watching', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '36', 'name' => 'Birding', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '37', 'name' => 'Blacksmithing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '38', 'name' => 'Blobbing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '39', 'name' => 'Blogging', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '40', 'name' => 'BMX', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '41', 'name' => 'Board ', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '42', 'name' => 'Boating', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '43', 'name' => 'Bobsledding', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '44', 'name' => 'Body Building', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '45', 'name' => 'Bonsai Tree', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '46', 'name' => 'Bookbinding', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '47', 'name' => 'Boomerangs', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '48', 'name' => 'Bowling', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '49', 'name' => 'Boxing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '50', 'name' => 'Brewing Beer', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '51', 'name' => 'Bridge Building', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '52', 'name' => 'Bringing Food To The Disabled', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '53', 'name' => 'Building A House For Habitat For Humanity', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '54', 'name' => 'Building Dollhouses', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '55', 'name' => 'Bungee Jumping', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '56', 'name' => 'Butterfly Watching', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '57', 'name' => 'Button ', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '58', 'name' => 'Cake Decorating', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '59', 'name' => 'Calligraphy', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '60', 'name' => 'Camping', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '61', 'name' => 'Candle Making', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '62', 'name' => 'Canoeing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '63', 'name' => 'Canyon Swinging', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '64', 'name' => 'Car Racing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '65', 'name' => 'Cardio Workout', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '66', 'name' => 'Cardstacking', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '67', 'name' => 'Cartooning', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '68', 'name' => 'Casino Gambling', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '69', 'name' => 'Cave Diving', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '70', 'name' => 'Ceramics', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '71', 'name' => 'Cheerleading', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '72', 'name' => 'Chess', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '73', 'name' => 'Church/church activities', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '74', 'name' => 'Cigar Smoking', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '75', 'name' => 'Cliff Diving', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '76', 'name' => 'Cloud Watching', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '77', 'name' => 'Coin ', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '78', 'name' => ' Antiques', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '79', 'name' => ' Artwork', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '80', 'name' => ' Hats', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '81', 'name' => '  Albums', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '82', 'name' => ' RPM Records', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '83', 'name' => '  Cards (Baseball', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '84', 'name' => ' Football', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '85', 'name' => ' Basketball', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '86', 'name' => ' Hockey)', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '87', 'name' => ' Swords', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '88', 'name' => 'Coloring', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '89', 'name' => 'Compose ', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '90', 'name' => 'Computer activities', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '91', 'name' => 'Contact Juggling', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '92', 'name' => 'Conworlding', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '93', 'name' => 'Cooking', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '94', 'name' => 'Cosplay', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '95', 'name' => 'Crafts', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '96', 'name' => 'Crafts (unspecified)', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '97', 'name' => 'Crochet', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '98', 'name' => 'Crocheting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '99', 'name' => 'Cross-Stitch', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '100', 'name' => 'Crossword Puzzles', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '101', 'name' => 'Cycling', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '102', 'name' => 'Darts', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '103', 'name' => 'Diecast Collectibles', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '104', 'name' => 'Digital Photography', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '105', 'name' => 'Diving', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '106', 'name' => 'Dodgeball', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '107', 'name' => 'Dolls', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '108', 'name' => 'Dominoes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '109', 'name' => 'Downhill Mountain Biking', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '110', 'name' => 'Downhill Skateboarding', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '111', 'name' => 'Drawing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '112', 'name' => 'Dumpster Diving', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '113', 'name' => 'Eating out', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '114', 'name' => 'Courses', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '115', 'name' => 'Electronics', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '116', 'name' => 'Embroidery', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '117', 'name' => 'Entertaining', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '118', 'name' => 'Exercise (aerobics', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '119', 'name' => ' weights)', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '120', 'name' => 'Falconry', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '121', 'name' => 'Fast cars', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '122', 'name' => 'Felting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '123', 'name' => 'Fencing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '124', 'name' => 'Fire Poi', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '125', 'name' => 'Fishing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '126', 'name' => 'Floorball', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '127', 'name' => 'Floral Arrangements', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '128', 'name' => 'Flowboarding', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '129', 'name' => 'Fly Fishing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '130', 'name' => 'Fly Hunting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '131', 'name' => 'Fly Tying', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '132', 'name' => 'Football', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '133', 'name' => 'Four Wheeling', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '134', 'name' => 'Free Climbing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '135', 'name' => 'Freshwater Aquariums', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '136', 'name' => 'Frisbee Golf – Frolf', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '137', 'name' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '138', 'name' => 'Garage Saleing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '139', 'name' => 'Gardening', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '140', 'name' => 'Genealogy', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '141', 'name' => 'Geocaching', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '142', 'name' => 'Ghost Hunting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '143', 'name' => 'Glowsticking', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '144', 'name' => 'Gnoming', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '145', 'name' => 'Go Kart Racing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '146', 'name' => 'Going to movies', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '147', 'name' => 'Golf', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '148', 'name' => 'Grip Strength', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '149', 'name' => 'Guitar', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '150', 'name' => 'Gun ', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '151', 'name' => 'Gunsmithing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '152', 'name' => 'Gymnastics', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '153', 'name' => 'Gyotaku', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '154', 'name' => 'Handwriting Analysis', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '155', 'name' => 'Hang gliding', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '156', 'name' => 'Herping', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '157', 'name' => 'Highlining', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '158', 'name' => 'Hiking', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '159', 'name' => 'Home Brewing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '160', 'name' => 'Home Repair', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '161', 'name' => 'Home Theater', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '162', 'name' => 'Horseback Riding', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '163', 'name' => 'Hot air ballooning', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '164', 'name' => 'Hula Hooping', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '165', 'name' => 'Hunting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '166', 'name' => 'Ice Climbing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '167', 'name' => 'Ice Cross Downhill', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '168', 'name' => 'Ice Diving', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '169', 'name' => 'Ice Fishing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '170', 'name' => 'Ice Skating', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '171', 'name' => 'Illusion', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '172', 'name' => 'Impersonations', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '173', 'name' => 'Inline Skating', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '174', 'name' => 'Internet', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '175', 'name' => 'Inventing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '176', 'name' => 'Jet Engines', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '177', 'name' => 'Jetboarding', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '178', 'name' => 'Jewelry Making', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '179', 'name' => 'Jigsaw Puzzles', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '180', 'name' => 'Jousting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '181', 'name' => 'Juggling', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '182', 'name' => 'Jump Roping', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '183', 'name' => 'Kayaking', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '184', 'name' => 'Keep A Journal', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '185', 'name' => 'Kitchen Chemistry', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '186', 'name' => 'Kite Boarding', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '187', 'name' => 'Kites', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '188', 'name' => 'Knitting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '189', 'name' => 'Knotting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '190', 'name' => 'Lacrosse', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '191', 'name' => 'Lasers', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '192', 'name' => 'Lawn Darts', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '193', 'name' => 'Learn to Play Poker', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '194', 'name' => 'Learning A Foreign Language', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '195', 'name' => 'Learning An Instrument', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '196', 'name' => 'Learning To Pilot A Plane', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '197', 'name' => 'Leathercrafting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '198', 'name' => 'Legos', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '199', 'name' => 'Letterboxing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '200', 'name' => 'Listening to music', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '201', 'name' => 'Locksport', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '202', 'name' => 'Luge / Skeleton', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '203', 'name' => 'Macramé', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '204', 'name' => 'Magic', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '205', 'name' => 'Making Model Cars', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '206', 'name' => 'Marksmanship', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '207', 'name' => 'Martial Arts', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '208', 'name' => 'Matchstick Modeling', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '209', 'name' => 'Meditation', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '210', 'name' => 'Metal Detecting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '211', 'name' => 'Microscopy', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '212', 'name' => 'Model Railroading', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '213', 'name' => 'Model Rockets', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '214', 'name' => 'Modeling Ships', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '215', 'name' => 'Models', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '216', 'name' => 'Motocross', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '217', 'name' => 'Motorcycle Stunts', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '218', 'name' => 'Motorcycles', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '219', 'name' => 'Mountain Biking', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '220', 'name' => 'Mountain Boarding', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '221', 'name' => 'Mountain Climbing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '222', 'name' => 'al Instruments', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '223', 'name' => 'Nail Art', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '224', 'name' => 'Needlepoint', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '225', 'name' => 'Noodling', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '226', 'name' => 'Off Road Driving', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '227', 'name' => 'Origami', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '228', 'name' => 'Owning An Antique Car', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '229', 'name' => 'Paintball', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '230', 'name' => 'Painting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '231', 'name' => 'Papermache', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '232', 'name' => 'Papermaking', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '233', 'name' => 'Parachuting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '234', 'name' => 'Paragliding or Power Paragliding', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '235', 'name' => 'Parkour', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '236', 'name' => 'People Watching', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '237', 'name' => 'Photography', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '238', 'name' => 'Piano', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '239', 'name' => 'Pilates', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '240', 'name' => 'Pinochle', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '241', 'name' => 'Pipe Smoking', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '242', 'name' => 'Planking', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '243', 'name' => 'Playing music', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '244', 'name' => 'Playing team sports', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '245', 'name' => 'Pole Dancing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '246', 'name' => 'Pottery', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '247', 'name' => 'Powerboking', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '248', 'name' => 'Protesting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '249', 'name' => 'Puppetry', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '250', 'name' => 'Pyrotechnics', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '251', 'name' => 'Quilting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '252', 'name' => 'R/C Boats', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '253', 'name' => 'R/C Cars', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '254', 'name' => 'R/C Helicopters', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '255', 'name' => 'R/C Planes', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '256', 'name' => 'Racing Pigeons', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '257', 'name' => 'Rafting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '258', 'name' => 'Rapping', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '259', 'name' => 'Reading', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '260', 'name' => 'Reading To The Elderly', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '261', 'name' => 'Renaissance Faire', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '262', 'name' => 'Rescuing Abused Or Abandoned Animals', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '263', 'name' => 'Robotics', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '264', 'name' => 'Rock Balancing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '265', 'name' => 'Rock Climbing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '266', 'name' => 'Rock Collecting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '267', 'name' => 'Rockets', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '268', 'name' => 'Rocking AIDS Babies', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '269', 'name' => 'Roleplaying', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '270', 'name' => 'Roller Derby', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '271', 'name' => 'Running', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '272', 'name' => 'Running of the Bulls', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '273', 'name' => 'Sailing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '274', 'name' => 'Saltwater Aquariums', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '275', 'name' => 'Sand Castles', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '276', 'name' => 'Sandboarding', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '277', 'name' => 'Scrapbooking', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '278', 'name' => 'Scuba Diving', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '279', 'name' => 'Self Defense', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '280', 'name' => 'Sewing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '281', 'name' => 'Shark Diving', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '282', 'name' => 'Shark Fishing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '283', 'name' => 'Shopping', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '284', 'name' => 'Singing In Choir', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '285', 'name' => 'Skateboarding', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '286', 'name' => 'Skeet Shooting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '287', 'name' => 'Sketching', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '288', 'name' => 'Skiing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '289', 'name' => 'Sky Diving', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '290', 'name' => 'Slack Lining', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '291', 'name' => 'Slingshots', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '292', 'name' => 'Slot Car Racing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '293', 'name' => 'Snorkeling', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '294', 'name' => 'Snow Skiing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '295', 'name' => 'Snowboarding', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '296', 'name' => 'Snowmobiling', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '297', 'name' => 'Soap Making', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '298', 'name' => 'Soccer', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '299', 'name' => 'Socializing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '300', 'name' => 'Speed Cubing (rubix cube)', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '301', 'name' => 'Spelunkering', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '302', 'name' => 'Squash', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '303', 'name' => 'Stamp ', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '304', 'name' => 'Storm Chasing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '305', 'name' => 'Storytelling', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '306', 'name' => 'Street Luge', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '307', 'name' => 'String Figures', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '308', 'name' => 'Surf Fishing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '309', 'name' => 'Surfingextreme', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '310', 'name' => 'Survival', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '311', 'name' => 'Swimming', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '312', 'name' => 'Swimming', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '313', 'name' => 'Tai Chi', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '314', 'name' => 'Tatting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '315', 'name' => 'Taxidermy', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '316', 'name' => 'Tea Tasting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '317', 'name' => 'Tennis', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '318', 'name' => 'Tesla Coils', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '319', 'name' => 'Tetris', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '320', 'name' => 'Textiles', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '321', 'name' => 'Tombstone Rubbing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '322', 'name' => 'Tool ', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '323', 'name' => 'Toy ', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '324', 'name' => 'Train ', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '325', 'name' => 'Train Spotting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '326', 'name' => 'Traveling', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '327', 'name' => 'Treasure Hunting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '328', 'name' => 'Triathlon', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '329', 'name' => 'Tutoring Children', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '330', 'name' => 'Ultimate Frisbee', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '331', 'name' => 'Urban Exploration', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '332', 'name' => 'Video Games', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '333', 'name' => 'Violin', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '334', 'name' => 'Volunteer', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '335', 'name' => 'Wakeboarding', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '336', 'name' => 'Walking', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '337', 'name' => 'Warhammer', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '338', 'name' => 'Watching sporting events', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '339', 'name' => 'Water Ski', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '340', 'name' => 'Waterfall Kayaking', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '341', 'name' => 'Weightlifting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '342', 'name' => 'White Water Rafting', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '343', 'name' => 'Windsurfing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '344', 'name' => 'Wine Making', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '345', 'name' => 'Wingsuit Flying', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '346', 'name' => 'Woodworking', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '347', 'name' => 'Working In A Food Pantry', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '348', 'name' => 'Working on cars', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '349', 'name' => 'World Record Breaking', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '350', 'name' => 'Wrestling', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '351', 'name' => 'Writing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '352', 'name' => 'Writing ', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '353', 'name' => 'Writing Songs', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '354', 'name' => 'Xpogo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '355', 'name' => 'Yoga', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '356', 'name' => 'YoYo', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '357', 'name' => 'Ziplining', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '358', 'name' => 'Zorbing', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '359', 'name' => 'Zumba', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ]);

        DB::table('personality_details')->insert([
            ['id' => '1', 'name' => '', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ]);
    }
}
